version: "3"
services:
  mpg-db:
    build:
      context: ./mpg-db
    image: mpg-db
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_ADMINISTRATOR_USERNAME}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_ADMINISTRATOR_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}
      - COUCHBASE_BUCKET_PASSWORD=${COUCHBASE_BUCKET_PASSWORD}
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - "~/couchbase/mpg-db:/opt/couchbase/var"